server:
  port: 8888

http:
  eureka:
    serviceUrl: 127.0.0.1

eureka:
  client:
    registerWithEureka: true  #是否需要将自己注入eureka（集群中需要）
    fetchRegistry: true #是否需要检索服务信息
    serviceUrl:
      defaultZone: http://${http.eureka.serviceUrl}:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    leaseRenewalIntervalInSeconds: 1
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    leaseExpirationDurationInSeconds: 2

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config #本地存储地址

  #配置文件在本地
  profiles:
    active: native

  logging:
    levels:
      org.springframework.boot.env.PropertySourcesLoader: TRACE
      org.springframework.cloud.config.server: DEBUG

